-- 01_setup.sql — sar-app-scan-gate objects. Scoped: one database, test roles, test users.
-- Nothing account-wide (no BIND revoke, no ALLOW_NPM_PACKAGE_DOWNLOAD change).
--
-- Roles
--   SAR_GATE_ADMIN    owns the gate: stages, tables, scan procs, scanner jobs
--   SAR_GATE_PUBLISH  owns REQUEST_PUBLISH + publisher job; only role that can create prod apps
--   SAR_GATE_BUILDER  vibe-coder / agent caller: write @INBOX, call procs, read own results
--   SAR_GATE_CONSUMER end users of published apps
USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS SAR_GATE_ADMIN;
CREATE ROLE IF NOT EXISTS SAR_GATE_PUBLISH;
CREATE ROLE IF NOT EXISTS SAR_GATE_BUILDER;
CREATE ROLE IF NOT EXISTS SAR_GATE_CONSUMER;
GRANT ROLE SAR_GATE_ADMIN TO ROLE SYSADMIN;
GRANT ROLE SAR_GATE_PUBLISH TO ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS SAR_GATE;
GRANT OWNERSHIP ON DATABASE SAR_GATE TO ROLE SAR_GATE_ADMIN COPY CURRENT GRANTS;
CREATE SCHEMA IF NOT EXISTS SAR_GATE.CORE;
CREATE SCHEMA IF NOT EXISTS SAR_GATE.PROD;    -- published apps live here
CREATE SCHEMA IF NOT EXISTS SAR_GATE.BUILD;   -- SAR build_job_location for publishes
GRANT OWNERSHIP ON SCHEMA SAR_GATE.CORE TO ROLE SAR_GATE_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA SAR_GATE.PROD TO ROLE SAR_GATE_PUBLISH COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA SAR_GATE.BUILD TO ROLE SAR_GATE_PUBLISH COPY CURRENT GRANTS;

CREATE COMPUTE POOL IF NOT EXISTS SAR_GATE_POOL
  MIN_NODES = 1 MAX_NODES = 2 INSTANCE_FAMILY = CPU_X64_XS AUTO_SUSPEND_SECS = 600;
GRANT USAGE, MONITOR ON COMPUTE POOL SAR_GATE_POOL TO ROLE SAR_GATE_ADMIN;
GRANT USAGE, MONITOR ON COMPUTE POOL SAR_GATE_POOL TO ROLE SAR_GATE_PUBLISH;

-- Warehouse used by procs and published apps (edit for your account)
SET GATE_WH = 'DEVCONTAINER_WH';
GRANT USAGE ON WAREHOUSE IDENTIFIER($GATE_WH) TO ROLE SAR_GATE_ADMIN;
GRANT USAGE ON WAREHOUSE IDENTIFIER($GATE_WH) TO ROLE SAR_GATE_PUBLISH;
GRANT USAGE ON WAREHOUSE IDENTIFIER($GATE_WH) TO ROLE SAR_GATE_BUILDER;

USE ROLE SAR_GATE_ADMIN;
USE SCHEMA SAR_GATE.CORE;

CREATE IMAGE REPOSITORY IF NOT EXISTS IMAGES;
-- Three trust zones
CREATE STAGE IF NOT EXISTS INBOX   ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE') DIRECTORY = (ENABLE = TRUE)
  COMMENT = 'builder-writable upload area';
CREATE STAGE IF NOT EXISTS FROZEN  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE') DIRECTORY = (ENABLE = TRUE)
  COMMENT = 'gate-only: exact scanned trees by digest';
CREATE STAGE IF NOT EXISTS RESULTS ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE') DIRECTORY = (ENABLE = TRUE)
  COMMENT = 'gate-only: scan / publish result JSON';

CREATE TABLE IF NOT EXISTS SCAN_RUNS (
  scan_id STRING, parent_scan_id STRING, submitted_by STRING, app_name STRING, app_path STRING,
  mode STRING, verdict STRING, digest STRING, counts VARIANT, findings VARIANT, rewrites VARIANT,
  diff STRING, ai_review VARIANT, error STRING,
  submitted_at TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(), finished_at TIMESTAMP_LTZ);

CREATE TABLE IF NOT EXISTS PUBLISH_LOG (
  publish_id STRING, scan_id STRING, digest STRING, app_name STRING, requested_by STRING,
  status STRING, service STRING, url STRING, detail VARIANT,
  requested_at TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP());

-- Builders see only their own submissions
CREATE OR REPLACE SECURE VIEW MY_SCANS AS
  SELECT scan_id, parent_scan_id, app_name, mode, verdict, digest, counts, findings, rewrites, diff,
         ai_review, error, submitted_at, finished_at
  FROM SCAN_RUNS WHERE submitted_by = CURRENT_USER();
CREATE OR REPLACE SECURE VIEW MY_PUBLISHES AS
  SELECT publish_id, scan_id, app_name, status, service, url, requested_at
  FROM PUBLISH_LOG WHERE requested_by = CURRENT_USER();

-- Grants: builder writes INBOX only; FROZEN/RESULTS are gate-only
GRANT USAGE ON DATABASE SAR_GATE TO ROLE SAR_GATE_BUILDER;
GRANT USAGE ON SCHEMA SAR_GATE.CORE TO ROLE SAR_GATE_BUILDER;
GRANT READ, WRITE ON STAGE INBOX TO ROLE SAR_GATE_BUILDER;
GRANT SELECT ON VIEW MY_SCANS TO ROLE SAR_GATE_BUILDER;
GRANT SELECT ON VIEW MY_PUBLISHES TO ROLE SAR_GATE_BUILDER;

-- Publisher: read frozen trees, write results, run its job, log publishes
GRANT USAGE ON DATABASE SAR_GATE TO ROLE SAR_GATE_PUBLISH;
GRANT USAGE, CREATE SERVICE, CREATE PROCEDURE ON SCHEMA SAR_GATE.CORE TO ROLE SAR_GATE_PUBLISH;
GRANT READ ON STAGE FROZEN TO ROLE SAR_GATE_PUBLISH;
GRANT READ, WRITE ON STAGE RESULTS TO ROLE SAR_GATE_PUBLISH;
GRANT READ ON IMAGE REPOSITORY IMAGES TO ROLE SAR_GATE_PUBLISH;
GRANT SELECT ON TABLE SCAN_RUNS TO ROLE SAR_GATE_PUBLISH;
GRANT SELECT, INSERT, UPDATE ON TABLE PUBLISH_LOG TO ROLE SAR_GATE_PUBLISH;

-- Consumers can use the prod schema (per-app USAGE is granted by the publisher)
USE ROLE SAR_GATE_PUBLISH;
GRANT USAGE ON SCHEMA SAR_GATE.PROD TO ROLE SAR_GATE_CONSUMER;
USE ROLE SAR_GATE_ADMIN;
GRANT USAGE ON DATABASE SAR_GATE TO ROLE SAR_GATE_CONSUMER;

-- ---------------------------------------------------------------------------
-- Test users (PAT auth, role-restricted). Remove for real deployments.
-- ---------------------------------------------------------------------------
USE ROLE ACCOUNTADMIN;
CREATE USER IF NOT EXISTS SAR_GATE_BUILDER_U  TYPE = PERSON DEFAULT_ROLE = SAR_GATE_BUILDER
  DEFAULT_WAREHOUSE = DEVCONTAINER_WH COMMENT = 'sar-app-scan-gate test user';
CREATE USER IF NOT EXISTS SAR_GATE_CONSUMER_U TYPE = PERSON DEFAULT_ROLE = SAR_GATE_CONSUMER
  DEFAULT_WAREHOUSE = DEVCONTAINER_WH COMMENT = 'sar-app-scan-gate test user';
GRANT ROLE SAR_GATE_BUILDER TO USER SAR_GATE_BUILDER_U;
GRANT ROLE SAR_GATE_CONSUMER TO USER SAR_GATE_CONSUMER_U;
-- PATs need a network-policy exemption for these users only (not account-wide)
CREATE AUTHENTICATION POLICY IF NOT EXISTS SAR_GATE.CORE.TEST_PAT_POLICY
  PAT_POLICY = (NETWORK_POLICY_EVALUATION = ENFORCED_NOT_REQUIRED);
ALTER USER SAR_GATE_BUILDER_U SET AUTHENTICATION POLICY SAR_GATE.CORE.TEST_PAT_POLICY;
ALTER USER SAR_GATE_CONSUMER_U SET AUTHENTICATION POLICY SAR_GATE.CORE.TEST_PAT_POLICY;
-- ENFORCED_NOT_REQUIRED still enforces an account network policy if one exists.
-- Allow only the test machine for these two users (replace the IP):
CREATE NETWORK POLICY IF NOT EXISTS SAR_GATE_TEST_NP ALLOWED_IP_LIST = ('<test-machine-ip>/32')
  COMMENT = 'sar-app-scan-gate test users only';
ALTER USER SAR_GATE_BUILDER_U SET NETWORK_POLICY = SAR_GATE_TEST_NP;
ALTER USER SAR_GATE_CONSUMER_U SET NETWORK_POLICY = SAR_GATE_TEST_NP;
